In [2]:
import numpy as np

In [5]:
my_list = [1,2,3]
arr=np.array(my_list)
arr

array([1, 2, 3])

In [8]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.arange(0,11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [19]:
np.zeros((2,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [20]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.linspace(0, 5, 100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.random.rand(5)

array([0.98280859, 0.03975421, 0.7157867 , 0.91234461, 0.4273705 ])

In [25]:
np.random.rand(5,5)

array([[0.65419424, 0.21373348, 0.53212377, 0.15159724, 0.2066977 ],
       [0.98648438, 0.51146521, 0.92695151, 0.59456463, 0.5250715 ],
       [0.79183434, 0.60977443, 0.52269166, 0.79094499, 0.91887147],
       [0.24602704, 0.11946511, 0.71792524, 0.33749385, 0.9454809 ],
       [0.21071414, 0.95698408, 0.52772785, 0.9393212 , 0.10887716]])

In [26]:
np.random.randn(5)

array([-0.09738197, -0.6176275 , -0.16276555, -0.54458173,  1.65068325])

In [27]:
np.random.randn(5,5)

array([[-0.0196128 ,  1.2889329 , -1.68038694, -0.01037916,  0.59969923],
       [ 1.10360724,  0.63403355, -0.64280534,  0.12122146,  0.05117444],
       [-0.52618479, -0.83231429, -0.43198863,  0.28228531,  1.30312645],
       [-0.5890542 , -1.23564659,  0.65543168,  0.59823166,  0.72690982],
       [ 1.60527016, -0.23143153, -0.41738474, -0.60996765, -0.37187609]])

In [30]:
np.random.randint(1,100, 10)

array([97, 16, 63, 65, 72, 24, 46, 21,  5,  7])

In [33]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
ranarr=np.random.randint(0,50, 10)
ranarr

array([39, 29, 17, 18,  1, 42,  4,  9, 22, 11])

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
ranarr

array([39, 29, 17, 18,  1, 42,  4,  9, 22, 11])

In [38]:
ranarr.max()

42

In [39]:
ranarr.min()

1

In [40]:
ranarr.argmax()

5

In [41]:
ranarr.argmin()

4

In [45]:
arr=arr.reshape(5,5)

In [46]:
arr.shape

(5, 5)

In [47]:
from numpy.random import randint

In [49]:
randint(2,5, 6)

array([4, 2, 3, 2, 2, 4])